
# Enable Optuna sweeps with:  python train.py -m hydra/sweeper=optuna hydra.sweeper.n_trials=20 hydra.sweeper.direction=maximize
# You can also set search spaces on the command line or here.
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    n_trials: 20
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.TPESampler
      consider_endpoints: true
      n_startup_trials: 5
    params:
      # Difficulty selection
      env.difficulty: choice(LOW, MEDIUM, HARD)
      # Core PPO search
      ppo.learning_rate: interval(1e-5, 1e-3)
      ppo.n_steps: choice(1024, 2048, 4096)
      ppo.batch_size: choice(32, 64, 128)
      ppo.gamma: interval(0.98, 0.999)
      ppo.gae_lambda: interval(0.9, 0.98)
      ppo.clip_range: interval(0.1, 0.3)
      ppo.ent_coef: interval(0.0, 0.02)
      ppo.vf_coef: interval(0.1, 1.0)
      ppo.max_grad_norm: interval(0.3, 1.0)
      n_envs: choice(2, 4, 8)
      seed: choice(0, 1, 2, 3)
      # Difficulty-related env params (used in MEDIUM/HARD; benign in LOW)
      env.cost_weight: interval(0.0, 0.1)
      env.budget_init: choice(5.0, 10.0, 20.0)
      env.fidelity_high_step_cost: choice(0.5, 1.0, 2.0)
      env.fidelity_low_step_cost: choice(0.0, 0.5)
      env.fidelity_high_noise_mult: choice(0.25, 0.5, 1.0)
